
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://<redacted>.cpc2-us-central.linodelke.net:443
  name: lke29910

users:
- name: lke29910-admin
  user:
    as-user-extra: {}
    token: <redacted>

contexts:
- context:
    cluster: lke29910
    namespace: default
    user: lke29910-admin
  name: lke29910-ctx

current-context: lke29910-ctx
